//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenKeyboard.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenKeyboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream piko {
            get {
                return ResourceManager.GetStream("piko", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream poka {
            get {
                return ResourceManager.GetStream("poka", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream poko {
            get {
                return ResourceManager.GetStream("poko", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream pon {
            get {
                return ResourceManager.GetStream("pon", resourceCulture);
            }
        }
        
        internal static byte[] スクリーンキーボードデータ {
            get {
                object obj = ResourceManager.GetObject("スクリーンキーボードデータ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   632
        ///241
        ///255
        ///157
        ///185
        ///235
        ///0
        ///
        ///
        ///1
        ///462
        ///4
        ///29
        ///26
        ///255
        ///236
        ///233
        ///216
        ///255
        ///172
        ///168
        ///153
        ///255
        ///0
        ///0
        ///0
        ///ＭＳ Ｐ明朝
        ///9.75
        ///Regular
        ///あ
        ///a
        ///が
        ///ga
        ///0
        ///0
        ///0
        ///0
        ///!
        ///!
        ///2
        ///1
        ///462
        ///30
        ///29
        ///26
        ///255
        ///236
        ///233
        ///216
        ///255
        ///172
        ///168
        ///153
        ///255
        ///0
        ///0
        ///0
        ///ＭＳ Ｐ明朝
        ///9.75
        ///Regular
        ///い
        ///i
        ///ぎ
        ///gi
        ///1
        ///1
        ///1
        ///1
        ///?
        ///?
        ///2
        ///1
        ///462
        ///56
        ///29
        ///26
        ///255
        ///236
        ///233
        ///216
        ///255
        ///172
        ///168
        ///153
        ///255
        ///0
        ///0
        ///0
        ///ＭＳ Ｐ明朝
        ///9.75
        ///Regular
        ///う
        ///u
        ///ぐ
        ///gu
        ///2
        ///2
        ///2
        ///2
        ///、
        ///,
        ///2
        ///1
        ///462
        ///82
        ///29
        ///26
        ///255
        ///236
        ///233
        ///216
        ///255
        ///172
        ///168
        ///153
        ///255
        ///0
        ///0
        ///0
        ///ＭＳ Ｐ明朝
        ///9 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string デフォルトデータ {
            get {
                return ResourceManager.GetString("デフォルトデータ", resourceCulture);
            }
        }
    }
}
